apiVersion: apps/v1
kind: Deployment
metadata:
  name: discord
  labels:
    app: discord
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discord
  template:
    metadata:
      labels:
        app: discord
    spec:
      containers:
        - name: discord
          image: rg.nl-ams.scw.cloud/genericdevelopment/discord:0.0.1
      imagePullSecrets:
        - name: regcred
