apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: discord
build:
  artifacts:
    - image: rg.nl-ams.scw.cloud/genericdevelopment/discord
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - kubernetes.yml
